---
- name: This sets up an httpd webserver
  hosts: apache
  sudo: yes
  tasks:
  - name: Install apache2
    apt: name=apache2 update_cache=yes state=latest
    
  - name: enabled mod_rewrite
    apache2_module: name=rewrite state=present
    notify:
      - restart apache2
      
      - name: apache2 listen on port 8080
        lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8080" state=present
        notify:
         - restart apache2

      - name: apache2 virtualhost on port 8080
        lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8080>" state=present
        notify:
          - restart apache2
          
      - name: apache2 default DocumentRoot
        lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^DocumentRoot /var/www/html" line="DocumentRoot /opt/hello-world.html" state=present
        notify:
          - restart apache2
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
