- name: example using security group rule descriptions
  ec2_group:
    name: "webserver"
    description: sg with rule descriptions
    vpc_id: '{{ ec2_vpc }}'
    region: '{{ ec2_region }}'
    rules: '{{ rule_list }}'
