# Basic provisioning example
- ec2:
    key_name: ansible-keypair
    instance_type: t2.micro
    image: ami-0f3eb76b0366d975f
    region: eu-west-1
    wait: yes
    group: webserver 
    count: 1
    vpc_subnet_id: subnet-65b12303
    assign_public_ip: yes
