# Basic provisioning example
- ec2:
    key_name: ansible-keypair
#    name: Webserver
    instance_type: t2.micro
    image: ami-01e6a0b85de033c99
    region: eu-west-1
    wait: yes
    group: webserver 
    count: 1
    instance_tags:
       Name: webserver
    vpc_subnet_id: subnet-65b12303
    assign_public_ip: yes
